---
name: Test-Trap
version: 0.1.1
author:
  - 'Eirik Berg Hanssen <Eirik-Berg.Hanssen@allverden.no>'
abstract: 'Trap exit codes, exceptions, output, etc.'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Config: 0
  Data::Dump: 0
  Exporter: 0
  File::Temp: 0
  IO::Handle: 0
  Test::Builder: 0
  Test::More: 0
  Test::Tester: 0.107
  base: 0
  constant: 0
  lib: 0
  perl: 5.6.0
  strict: 0
  version: 0
  warnings: 0
provides:
  Test::Trap:
    file: lib/Test/Trap.pm
    version: 0.1.1
  Test::Trap::Builder:
    file: lib/Test/Trap/Builder.pm
    version: 0.1.1
  Test::Trap::Builder::PerlIO:
    file: lib/Test/Trap/Builder/PerlIO.pm
    version: 0.1.1
  Test::Trap::Builder::SystemSafe:
    file: lib/Test/Trap/Builder/SystemSafe.pm
    version: 0.1.1
  Test::Trap::Builder::TempFile:
    file: lib/Test/Trap/Builder/TempFile.pm
    version: 0.1.1
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
