---
abstract: 'Trap exit codes, exceptions, output, etc.'
author:
  - 'Eirik Berg Hanssen <Eirik-Berg.Hanssen@allverden.no>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Trap
provides:
  Test::Trap:
    file: lib/Test/Trap.pm
    version: v0.2.3
  Test::Trap::Builder:
    file: lib/Test/Trap/Builder.pm
    version: v0.2.3
  Test::Trap::Builder::PerlIO:
    file: lib/Test/Trap/Builder/PerlIO.pm
    version: v0.2.3
  Test::Trap::Builder::SystemSafe:
    file: lib/Test/Trap/Builder/SystemSafe.pm
    version: v0.2.3
  Test::Trap::Builder::TempFile:
    file: lib/Test/Trap/Builder/TempFile.pm
    version: v0.2.3
requires:
  Carp: 0
  Data::Dump: 0
  Exporter: 0
  File::Temp: 0
  IO::Handle: 0
  Test::Builder: 0
  Test::More: 0
  Test::Tester: 0.107
  base: 0
  constant: 0
  lib: 0
  perl: v5.6.2
  strict: 0
  version: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.2.3
