--- #YAML:1.0
name:                Test-Trap
version:             0.1.2
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    base:                          0
    Carp:                          0
    Config:                        0
    constant:                      0
    Data::Dump:                    0
    Exporter:                      0
    File::Temp:                    0
    IO::Handle:                    0
    lib:                           0
    strict:                        0
    Test::Builder:                 0
    Test::More:                    0
    Test::Tester:                  0.107
    version:                       0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
